// NOLINTBEGIN
// DO NOT EDIT THIS FILE!
#pragma once

#include <sstream>

template <typename T>
T ConvertFromString(const std::string& str) {
  std::istringstream in(str);
  T value;
  in >> std::boolalpha >> value;

  return value;
}

// NOLINTEND
